### PR TITLE
added features

### PR DESCRIPTION
**Pull request by whyvn**
Dont know why you would want aimbot on no matter what.

### CODE REVIEW

**Comment by whyvn** [comment]
hold on, i just noticed your the guy from the chernos grass [code review](https://www.youtube.com/watch?v=2h5NX9tIdno&t=630s) while browsing through your repos and came accross your GLGrass.

**Comment by aymey** [comment]
## My (F18) boyfriend (M18) traded my nudes for a Minecraft anticheat bypass
Right.. So, to start off, me and my boyfriend (we'll call him Cameron) have been together for a year and half. I have always been self conscious about my looks (I'm very skinny) since I was little. Our relationship was wonderful until about 5 months ago when he started to make me feel like absolute shit by calling me names, making fun of me and how I look, talking shit behind my back to my girlfriends. For the first month this started I kept trying to talk to him and he would stop for a few days then do the same thing over again. I ended up breaking up but then got back together with him after a week. He hasn't done this again since our "breakup", and things were OK again.
Now, as mentioned in the title, he makes and sells a Minecraft hack. He would randomly text me threatening me (sometimes threatening to kill me) because he's angry someone called his Minecraft client bad and starts crying on the phone because someone called him bad at it. He even It would mentally and physically drain me. One time when I was at his house he literally forced me to talk to his "Minecraft friends" about how it's not bad.
Fast forward about two months, I get a message on Instagram. It's one of his friends sending an intimate video of me that Cameron secretly recorded (we were video calling.). That person sent screenshots of how he traded this video for an anti-cheat bypass...
This just happened. What do I even do now? Can we still repair this?
Thank you so much..

**Comment by whyvn** [comment]
just relised some of my code comments for trying to only aim assist when holding a weapon is still there. i tried like all day and cant find out how, half of the [mcp mappings](https://github.com/Techcable/mcp/blob/master/conf/fields.csv) dont work :( sorry

**Comment by whyvn** [comment]
reset is useful because if you disable a cheat you wouldn't want it to keep the settings. e.g. if i enable and set reach (which is broken) to 6 blocks and then i disable reach i will still have the 6 block reach active, reset function lets you do something when the user disables a cheat e.g. set reach back to 3 without altering the user preferences.

**Comment by whyvn** [comment]
Speed is currently broken, VClip has a bug (i think its minecrafts problem not mine though), and im fixing velocity and making it its own cheat prob tmr. also want to add "temporary modules", it will basically just execute the cheat once and then stop (useful for vclip). ill try to also do some UI changes and bug fixes tmr but idk. also please use [MCP Mapping Viewer](https://github.com/bspkrs/MCPMappingViewer) for accurate mapping since udp is limited, most other resources are outdated or dont provide useful and/or accurate information and more. maybe ill add it to the readme (as a contributor guide or something?).
dont merge rn

**Comment by whyvn** [comment]
i needed to cast the coords to double when calling the method. i would use doubles for x,y,z but i dont think we have `ImGui::InputDouble()` yet (havnt looked so dont quote me)
also i removed `PlayerControllerMP` for know since it was causing some injection issues. ill add it back once ive solved the problem

**Comment by whyvn** [comment]
i have to change `Phantom.*` to only run `reset()` once eventually. but right now its still practical since only one cheat uses this function currently.

**Comment by whyvn** [comment]
i spent a while on the velocity and but nothing really works. ive used `setVelocity (DDD)V` and `motion. D` with different conditions with player damage but it either:
- sometimes doesn't work randomly
- works all the time but disables velocity/ sets motion for a prolonged period.

some other clients use these exact same techniques and dont have these issues.
the reason for it sometimes not working could possible be because it takes to long (more than 1 seconds) to get the `player(Max)HurtTime()` and after it gets the data its too late and the player is no longer on the first second of damage taken.

and the reason for the prolonged one is because `player.getMaxHurtTime() > 0` could be from 10 to 0 which would be ten seconds of motion/velocity change.

**Review by Dispnser — APPROVED** [review]
LGTM

**Pull request merged**
